name: Extract invite.zip

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract invite.zip
      run: |
        unzip invite.zip -d extracted/
